# Generated by Django 4.2.3 on 2023-07-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
