# Generated by Django 4.2.3 on 2023-07-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='blog_numer',
            new_name='blog',
        ),
        migrations.AddField(
            model_name='comments',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
