# Generated by Django 4.2.3 on 2023-07-17 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_rename_blog_numer_comments_blog_comments_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='comment',
        ),
    ]
