# Generated by Django 4.2.3 on 2023-07-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_rename_post_comments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(default='none@none.com', max_length=255),
        ),
    ]
