# Generated by Django 4.2.3 on 2023-07-22 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_comments_name_alter_comments_time_stamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='artical',
            new_name='article',
        ),
    ]
