# Generated by Django 4.2.3 on 2023-07-22 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog_app', '0008_rename_artical_blog_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='group',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
            preserve_default='True',
        ),
    ]
