# Generated by Django 4.2.3 on 2023-07-22 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
